### ISSUE TITLE
Strength estimator crashes on empty password + others

### ISSUE THREAD

**Issue by stevenjohnstone** [trustelem/zxcvbn#1]
I added some fuzzing and found that there's various crashing bugs (indexes arrays outside of bounds) e.g with password "".

**Comment by vanackere** [comment]
Thanks for the report, I'll have a look ASAP.

**Comment by vanackere** [comment]
I fixed the obvious crashes and merged your fuzzing patches. I don't have much time right now but I intend to fixe every crash properly. Thanks !

**Comment by vanackere** [comment]
I'm running a new fuzzing session, but cannot find any new crash (for now). I will close this bug after a few days unless a new crash occurs...
