### ISSUE TITLE
Wrong testify dependency used

### ISSUE THREAD

**Issue by rustyx** [trustelem/zxcvbn#15]
This module uses `github.com/test-go/testify` which is an obsolete fork of `github.com/stretchr/testify`.

Consequently pulling this module in `go.mod` transitively pulls that obsolete dependency, which messes with auto-completion (risk of accidentally selecting the wrong package for `assert` and `require`).

```
require (
	github.com/test-go/testify v1.1.4 // indirect
	github.com/trustelem/zxcvbn v1.0.1
)
```

Thus hereby a request to use the correct dependency for [testify](https://github.com/stretchr/testify).

**Comment by vanackere** [comment]
Merged, thanks !
